apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tms-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
    - host: tms.local
      http:
        paths:
          - path: /api/ingest
            pathType: Prefix
            backend:
              service:
                name: ingestion-service
                port:
                  number: 8080
          - path: /api/registry
            pathType: Prefix
            backend:
              service:
                name: ingestion-service
                port:
                  number: 8080
          - path: /api/reports
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
          - path: /api/notify
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
          - path: /hubs/alarms
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
